version: '3.7'

services:

    app:
        build: .
        image: pwnedhub-dev
        expose:
            - 5000
        volumes:
            - .:/pwnedhub
        environment:
            - CONFIG=Production
            - DATABASE_HOST=db
        command: gunicorn --bind 0.0.0.0:5000 pwnedhub.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db

    spa:
        image: pwnedhub-dev
        expose:
            - 5001
        volumes:
            - .:/pwnedhub
        environment:
            - CONFIG=Production
        command: gunicorn --bind 0.0.0.0:5001 pwnedspa.wsgi:app --error-logfile - --log-level DEBUG

    api:
        image: pwnedhub-dev
        expose:
            - 5002
        volumes:
            - .:/pwnedhub
            - ~/inbox:/tmp/inbox # local mapping to INBOX_PATH
        environment:
            - CONFIG=Production
            - DATABASE_HOST=db
            - REDIS_URL=redis://redis:6379/0
            - INBOX_PATH=/tmp/inbox # writable location for Gunicorn
        command: gunicorn --bind 0.0.0.0:5002 --worker-class eventlet --workers 1 pwnedapi.wsgi:app --error-logfile - --log-level DEBUG
        depends_on:
            - db
            - redis

    worker:
        image: pwnedhub-dev
        volumes:
            - .:/pwnedhub
        environment:
            - CONFIG=Production
            - DATABASE_HOST=db
            - REDIS_URL=redis://redis:6379/0
        command: rq worker -u redis://redis:6379/0 pwnedhub-tasks
        depends_on:
            - db
            - redis

    proxy:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./proxy/proxy_params:/etc/nginx/proxy_params:ro
        depends_on:
            - app
            - spa
            - api

    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=adminpass
            - MYSQL_DATABASE=pwnedhub
            - MYSQL_USER=pwnedhub
            - MYSQL_PASSWORD=dbconnectpass
        volumes:
            - ./pwnedhub.sql:/docker-entrypoint-initdb.d/pwnedhub.sql:ro

    redis:
        image: redis
